namespace Enigma;

/// <summary>
/// The bigram tables this library ships with, under the names their booklets used.
///
/// A set was named by a codeword and held nine tables lettered A to H and J, with a
/// Tauschtafelplan saying which applied on which day. Only tables transcribed from a
/// published scan of an original appear here, and each is checked before it ships:
/// every one of the 676 bigrams present, every entry paired with its mirror, and no
/// bigram enciphering to itself.
///
/// These are from the set "Quelle", booklet Prüf-Nr. 2499, reproduced by the Crypto
/// Museum. It is the set U-534 was using on 1 May 1945.
/// </summary>
public static class BigramTables
{
    /// <summary>
    /// Tafel A of "Quelle". The four entries message P1030690 needed — FN, HC, GV
    /// and ET — are exactly those published with the working of that message.
    /// </summary>
    public static BigramTable QuelleA { get; } = BigramTable.Parse(QuelleAEntries);

    /// <summary>Tafel B of "Quelle".</summary>
    public static BigramTable QuelleB { get; } = BigramTable.Parse(QuelleBEntries);

    /// <summary>Tafel C of "Quelle".</summary>
    public static BigramTable QuelleC { get; } = BigramTable.Parse(QuelleCEntries);

    /// <summary>Tafel D of "Quelle".</summary>
    public static BigramTable QuelleD { get; } = BigramTable.Parse(QuelleDEntries);

    /// <summary>
    /// Tafel E of "Quelle". Six cells of its first two rows are covered by later
    /// hand-written ink on the scan and were recovered from their mirrors rather
    /// than read: on an involution the mirror is the same fact written twice.
    /// </summary>
    public static BigramTable QuelleE { get; } = BigramTable.Parse(QuelleEEntries);

    /// <summary>Tafel F of "Quelle".</summary>
    public static BigramTable QuelleF { get; } = BigramTable.Parse(QuelleFEntries);

    /// <summary>
    /// Tafel G of "Quelle". Its two pages are the poorest scan in the booklet;
    /// eight cells were too blurred to read off and were settled by the rest of
    /// the table, then checked against the glyph at magnification.
    /// </summary>
    public static BigramTable QuelleG { get; } = BigramTable.Parse(QuelleGEntries);

    // Written once through: each entry implies its reverse, and BigramTable builds
    // the other direction itself.

    private const string QuelleAEntries =
        "AA=QG AB=CH AC=NF AD=WT AE=OL AF=ER AG=JE AH=LD AI=ZS AJ=HH AK=PZ AL=UX AM=DB AN=RT " +
        "AO=BY AP=SK AQ=TV AR=YI AS=VF AT=MM AU=FO AV=XN AW=IP AX=NQ AY=KL AZ=GG BA=FS BB=PH " +
        "BC=DW BD=SR BE=GT BF=RA BG=UQ BH=CU BI=VO BJ=MC BK=QX BL=TM BM=VC BN=EX BO=YU BP=JM " +
        "BQ=EG BR=IS BS=OV BT=LJ BU=XR BV=FL BW=IK BX=UK BZ=WN CA=JH CB=OR CC=VJ CD=NM CE=HF " +
        "CF=XV CG=DO CI=UD CJ=ZP CK=XI CL=GE CM=RL CN=TR CO=ZB CP=MJ CQ=YO CR=KQ CS=FE CT=IU " +
        "CV=LT CW=QS CX=SZ CY=NU CZ=IN DA=EJ DC=NH DD=QK DE=SG DF=LQ DG=IF DH=UG DI=HO DJ=OA " +
        "DK=FW DL=JK DM=HC DN=FQ DP=YL DQ=RH DR=PM DS=ON DT=RO DU=GQ DV=TJ DX=WP DY=ZG DZ=KN " +
        "EA=RJ EB=GI EC=PD ED=MH EE=TD EF=OQ EH=LF EI=HR EK=YR EL=QV EM=KH EN=SF EO=NT EP=JV " +
        "EQ=FG ES=VR ET=ZZ EU=LW EV=ID EW=UM EY=WF EZ=LO FA=PS FB=LM FC=NZ FD=JP FF=HL FH=LB " +
        "FI=RE FJ=UA FK=ZL FM=HX FN=KY FP=ME FR=XX FT=TH FU=PV FV=KG FX=VT FY=GL FZ=IX GA=JS " +
        "GB=QD GC=HZ GD=RF GF=TP GH=YC GJ=KD GK=ZU GM=II GN=LV GO=PP GP=JY GR=NC GS=ST GU=MT " +
        "GV=UU GW=XK GX=TB GY=HS GZ=WJ HA=QN HB=TG HD=IZ HE=VL HG=ZX HI=SM HJ=MP HK=OG HM=KA " +
        "HN=WY HP=NO HQ=XE HT=JC HU=YF HV=US HW=LL HY=RX IA=KV IB=OP IC=TF IE=WW IG=YH IH=VZ " +
        "IJ=MG IL=XT IM=SC IO=LE IQ=WH IR=YY IT=JJ IV=RQ IW=ZN IY=TA JA=MR JB=OC JD=SP JF=SS " +
        "JG=YM JI=NX JL=UH JN=ZQ JO=LH JQ=KK JR=OF JT=ZE JU=LN JW=VV JX=SA JZ=WL KB=RC KC=NL " +
        "KE=ZI KF=PX KI=VH KJ=UF KM=YN KO=VA KP=OT KR=SI KS=XZ KT=MF KU=QP KW=TY KX=WC KZ=LI " +
        "LA=PB LC=MX LG=ZK LK=OH LP=RD LR=SE LS=XG LU=YT LX=NJ LY=UO LZ=TN MA=ZO MB=OJ MD=RN " +
        "MI=SH MK=TI ML=YK MN=QI MO=NA MQ=WR MS=QQ MU=TT MV=XP MW=PR MY=VK MZ=UI NB=TL ND=OM " +
        "NE=PJ NG=ZJ NI=YG NK=QO NN=XC NP=QF NR=WE NS=RV NV=SJ NW=VP NY=UW OB=YQ OD=PU OE=ZW " +
        "OI=QC OK=WQ OO=SN OS=XH OU=RZ OW=UC OX=XM OY=WK OZ=TS PA=RR PC=YW PE=TX PF=ZD PG=QA " +
        "PI=XS PK=TW PL=VX PN=UL PO=WG PQ=SO PT=VM PW=YE PY=RM QB=VW QE=RP QH=YJ QJ=TZ QL=YP " +
        "QM=UV QR=UJ QT=ZR QU=SW QW=RI QY=WM QZ=XJ RB=WU RG=TQ RK=ZT RS=WA RU=VI RW=YS RY=SL " +
        "SB=YV SD=WX SQ=ZM SU=TC SV=WO SX=UN SY=XD TE=XO TK=ZV TO=UB TU=XL UE=ZC UP=YA UR=VE " +
        "UT=XW UY=WD UZ=YX VB=WS VD=YZ VG=XU VN=ZH VQ=WB VS=XQ VU=YD VY=XF WI=ZA WV=XB WZ=YB " +
        "XA=ZY XY=ZF";

    private const string QuelleBEntries =
        "AA=HN AB=PK AC=SB AD=CJ AE=VU AF=YO AG=RV AH=BE AI=XG AJ=QL AK=LH AL=EC AM=TQ AN=ZS " +
        "AO=DP AP=GG AQ=JO AR=NH AS=KX AT=MZ AU=OW AV=UT AW=FE AX=WJ AY=CS AZ=VH BA=SF BB=ER " +
        "BC=YK BD=QG BF=DH BG=VN BH=ZW BI=GP BJ=KQ BK=NA BL=PZ BM=UH BN=IS BO=XD BP=JL BQ=FI " +
        "BR=OC BS=MT BT=RO BU=TY BV=WU BW=HQ BX=EN BY=LR BZ=XR CA=IN CB=KS CC=DL CD=VB CE=OM " +
        "CF=EJ CG=UQ CH=ZY CI=LM CK=NP CL=HS CM=FD CN=ST CO=ZU CP=RH CQ=GM CR=JR CT=ML CU=PQ " +
        "CV=TK CW=SM CX=KJ CY=QP CZ=TH DA=VX DB=HJ DC=NW DD=RL DE=VS DF=YH DG=FX DI=QU DJ=HW " +
        "DK=MG DM=EZ DN=HF DO=UE DQ=PO DR=LT DS=GJ DT=IF DU=WQ DV=KM DW=OR DX=TN DY=XS DZ=SX " +
        "EA=HL EB=NK ED=JF EE=SO EF=WD EG=RX EH=ZO EI=FA EK=MP EL=TV EM=YC EO=OT EP=KD EQ=XW " +
        "ES=UB ET=VZ EU=GN EV=LD EW=PT EX=IP EY=HC FB=PG FC=HI FF=YS FG=OH FH=KB FJ=RT FK=VP " +
        "FL=ZD FM=GE FN=NB FO=UN FP=SI FQ=MK FR=QB FS=IH FT=XM FU=LK FV=NU FW=MS FY=PW FZ=JJ " +
        "GA=WH GB=JN GC=QD GD=MR GF=IV GH=SK GI=NN GK=LP GL=VJ GO=KN GQ=XO GR=OE GS=YA GT=RR " +
        "GU=JH GV=YI GW=HH GX=ZF GY=TD GZ=LF HA=MI HB=OD HD=JZ HE=RD HG=UL HK=PD HM=WO HO=JA " +
        "HP=NR HR=TI HT=IB HU=VL HV=QJ HX=XI HY=LV HZ=KO IA=QN IC=TP ID=MW IE=SA IG=WN II=RK " +
        "IJ=XJ IK=ZL IL=ND IM=KP IO=VF IQ=SR IR=YE IT=UZ IU=LN IW=JC IX=KK IY=VW IZ=UX JB=MU " +
        "JD=KG JE=OF JG=LL JI=ZQ JK=OI JM=SH JP=XE JQ=OK JS=RA JT=WL JU=PR JV=TS JW=UG JX=WZ " +
        "JY=VD KA=YQ KC=NM KE=ZI KF=UA KH=NF KI=XV KL=SS KR=VA KT=QR KU=TB KV=WT KW=PI KY=PM " +
        "KZ=YM LA=SD LB=MO LC=YG LE=NT LG=XB LI=OG LJ=ZZ LO=PA LQ=US LS=XF LU=TF LW=VQ LX=NE " +
        "LY=RM LZ=WR MA=TG MB=OP MC=ZK MD=NG ME=YP MF=SQ MH=PY MJ=QC MM=WX MN=TZ MQ=PU MV=SE " +
        "MX=YW MY=RI NC=ZR NI=RZ NJ=TO NL=VG NO=YL NQ=OY NS=RJ NV=QK NX=UV NY=ZT NZ=VM OA=QW " +
        "OB=SP OJ=ZV OL=UJ ON=PS OO=UD OQ=WF OS=ZA OU=YB OV=RP OX=TM OZ=XU PB=UI PC=QX PE=ZX " +
        "PF=RE PH=TA PJ=UO PL=XA PN=SC PP=YN PV=QF PX=ZG QA=WM QE=ZN QH=SL QI=VT QM=WA QO=XK " +
        "QQ=RB QS=YZ QT=RN QV=TE QY=WI QZ=TT RC=UK RF=WB RG=ZP RQ=SG RS=VV RU=XH RW=YU RY=XQ " +
        "SJ=VC SN=ZC SU=TC SV=XY SW=YY SY=UF SZ=WP TJ=XL TL=UC TR=ZE TU=VE TW=YX TX=UP UM=VI " +
        "UR=ZB UU=VK UW=XZ UY=YD VO=XC VR=XX VY=ZH WC=YV WE=XT WG=YR WK=YJ WS=XN WV=YF WW=ZJ " +
        "WY=XP YT=ZM";

    private const string QuelleCEntries =
        "AA=UM AB=KH AC=OP AD=NE AE=TJ AF=IN AG=ZL AH=RV AI=FS AJ=CH AK=JZ AL=MS AM=YK AN=GB " +
        "AO=QZ AP=XI AQ=LW AR=PC AS=WX AT=JN AU=VE AV=DO AW=BF AX=SQ AY=HM AZ=EB BA=WO BB=PN " +
        "BC=LF BD=FA BE=RI BG=ME BH=SZ BI=OG BJ=KT BK=ID BL=ZX BM=CT BN=EQ BO=DZ BP=YT BQ=JA " +
        "BR=VO BS=NW BT=GF BU=DB BV=XX BW=QI BX=TA BY=UT BZ=HC CA=LM CB=WD CC=NM CD=IV CE=PV " +
        "CF=QA CG=OZ CI=VV CJ=HT CK=GQ CL=ZR CM=RO CN=JF CO=SB CP=ZG CQ=YA CR=FI CS=MK CU=XN " +
        "CV=EL CW=TS CX=UD CY=DE CZ=KN DA=LQ DC=WT DD=PG DF=OA DG=VI DH=ZO DI=QS DJ=KC DK=NA " +
        "DL=SI DM=YE DN=RC DP=XB DQ=JV DR=MX DS=FE DT=UB DU=TY DV=IH DW=EG DX=GK DY=HJ EA=XL " +
        "EC=NR ED=TN EE=ZC EF=HA EH=YO EI=PQ EJ=OV EK=IR EM=KK EN=LV EO=XS EP=WI ER=GW ES=RZ " +
        "ET=QM EU=SL EV=FY EW=JR EX=VA EY=UH EZ=LI FB=PJ FC=UQ FD=VU FF=GI FG=NI FH=QD FJ=WL " +
        "FK=ZH FL=SU FM=YQ FN=RA FO=XE FP=OK FQ=HZ FR=MB FT=IB FU=TD FV=LA FW=VC FX=KZ FZ=JK " +
        "GA=UO GC=MO GD=RR GE=LT GG=ZZ GH=SE GJ=RY GL=YZ GM=QW GN=OD GO=HP GP=NC GR=PS GS=KA " +
        "GT=IY GU=XV GV=TQ GX=WB GY=XP GZ=JD HB=QO HD=NK HE=MA HF=KQ HG=OX HH=SV HI=ZU HK=PA " +
        "HL=TV HN=YW HO=RL HQ=WF HR=UX HS=VR HU=SA HV=LL HW=XK HX=JY HY=IK IA=NP IC=YU IE=RF " +
        "IF=UK IG=ZN II=QU IJ=OM IL=MH IM=XG IO=YH IP=SN IQ=PX IS=LC IT=JH IU=VZ IW=TG IX=WQ " +
        "IZ=KW JB=RK JC=NU JE=UZ JG=OB JI=SW JJ=QF JL=PE JM=ZA JO=XY JP=MV JQ=KF JS=TL JT=WV " +
        "JU=YC JW=VL JX=LO KB=ZY KD=LB KE=VX KG=OS KI=NY KJ=SS KL=YI KM=RX KO=QK KP=UA KR=PP " +
        "KS=LZ KU=WM KV=TC KX=MQ KY=TT LD=NT LE=RT LG=ZJ LH=QB LJ=YX LK=SG LN=OI LP=WZ LR=UV " +
        "LS=MM LU=XC LX=VG LY=QQ MC=PB MD=VT MF=OR MG=ZE MI=UR MJ=QY ML=TZ MN=WA MP=RE MR=YV " +
        "MT=SX MU=NG MW=ZP MY=XA MZ=QC NB=QG ND=SY NF=WK NH=ZW NJ=UF NL=XU NN=PZ NO=TP NQ=VM " +
        "NS=YM NV=OO NX=RB NZ=QV OC=UY OE=WR OF=ZS OH=RG OJ=TB OL=QX ON=UJ OQ=XZ OT=PY OU=SD " +
        "OW=YD OY=VB PD=SO PF=XM PH=ZT PI=UN PK=WG PL=YR PM=QN PO=TW PR=VQ PT=US PU=RM PW=SC " +
        "QE=TU QH=UP QJ=WP QL=ZM QP=SR QR=VK QT=RD RH=WW RJ=YG RN=ZB RP=VF RQ=TX RS=UE RU=SJ " +
        "RW=XQ SF=WN SH=UI SK=XW SM=ZQ SP=TF ST=YB TE=VY TH=ZV TI=WE TK=UW TM=XR TO=YJ TR=VD " +
        "UC=VW UG=WH UL=XJ UU=YS VH=XT VJ=ZD VN=YL VP=WY VS=XD WC=YN WJ=XO WS=ZF WU=YY XF=YP " +
        "XH=ZK YF=ZI";

    private const string QuelleDEntries =
        "AA=TN AB=KH AC=OQ AD=IN AE=PB AF=NV AG=RJ AH=JG AI=UO AJ=ZR AK=QX AL=MP AM=GD AN=DZ " +
        "AO=HC AP=YI AQ=VV AR=SE AS=WJ AT=XY AU=CL AV=JR AW=LI AX=BK AY=EF AZ=FT BA=KN BB=RR " +
        "BC=WU BD=SQ BE=JD BF=OA BG=HS BH=EV BI=GP BJ=ME BL=QH BM=PT BN=VR BO=ZF BP=YX BQ=TV " +
        "BR=LS BS=DA BT=NC BU=CZ BV=XE BW=UG BX=VA BY=FH BZ=ID CA=ZK CB=PJ CC=IT CD=LA CE=TB " +
        "CF=MX CG=JW CH=DI CI=HZ CJ=NK CK=EM CM=KX CN=GV CO=YL CP=FB CQ=OI CR=QN CS=UW CT=VK " +
        "CU=YA CV=RB CW=SX CX=WE CY=XL DB=IH DC=GJ DD=TQ DE=ZX DF=JA DG=HK DH=VQ DJ=LM DK=YJ " +
        "DL=SA DM=PO DN=WB DO=FM DP=NA DQ=OX DR=MC DS=KE DT=XS DU=RV DV=YQ DW=EA DX=QC DY=UB " +
        "EB=TH EC=OM ED=IK EE=QY EG=MA EH=NP EI=TZ EJ=PF EK=SJ EL=US EN=LX EO=ZA EP=HG EQ=JK " +
        "ER=GM ES=RN ET=YD EU=XB EW=KR EX=WP EY=VD EZ=FA FC=PA FD=MJ FE=QR FF=KB FG=WA FI=JN " +
        "FJ=HW FK=NG FL=UP FN=LD FO=IA FP=RE FQ=SM FR=ZU FS=GA FU=OD FV=YM FW=TE FX=VN FY=UD " +
        "FZ=XH GB=ZD GC=WY GE=MT GF=PL GG=VI GH=ZO GI=LP GK=TX GL=JH GN=UK GO=YT GQ=IX GR=OT " +
        "GS=XO GT=SU GU=HA GW=NZ GX=QB GY=RH GZ=KK HB=TK HD=ZC HE=MM HF=QK HH=JP HI=SG HJ=XV " +
        "HL=RZ HM=IQ HN=PX HO=WM HP=YF HQ=LF HR=ST HT=XJ HU=OG HV=KA HX=NM HY=TT IB=OO IC=VG " +
        "IE=ZH IF=RX IG=NS II=LU IJ=KT IL=JU IM=TA IO=YV IP=SC IR=MH IS=PZ IU=QE IV=UY IW=XQ " +
        "IY=VT IZ=WR JB=NQ JC=SO JE=NI JF=UM JI=WZ JJ=QU JL=OK JM=ZB JO=MV JQ=RL JS=KD JT=YY " +
        "JV=PR JX=LK JY=VB JZ=XA KC=UE KF=NX KG=VY KI=OZ KJ=QA KL=PV KM=ZQ KO=RP KP=MZ KQ=OV " +
        "KS=XC KU=TJ KV=WH KW=YB KY=MW KZ=LB LC=QP LE=UA LG=RT LH=ZM LJ=YK LL=OS LN=TP LO=NE " +
        "LQ=WO LR=XX LT=PD LV=MR LW=SZ LY=UQ LZ=VP MB=ZE MD=NO MF=TG MG=YO MI=OB MK=SS ML=XZ " +
        "MN=QJ MO=WW MQ=VL MS=PH MU=RA MY=UI NB=ZS ND=TL NF=VZ NH=XG NJ=SB NL=PM NN=UU NR=OY " +
        "NT=WG NU=YZ NW=QT NY=RC OC=UN OE=ZZ OF=SK OH=WK OJ=QS OL=RG ON=PY OP=VX OR=XU OU=YG " +
        "OW=TY PC=UZ PE=WD PG=VU PI=ZY PK=RW PN=TC PP=UR PQ=SW PS=QF PU=ZW PW=XM QD=TW QG=ZJ " +
        "QI=UV QL=SY QM=RY QO=YW QQ=XD QV=WT QW=VC QZ=TD RD=WN RF=SI RI=ZV RK=XP RM=YC RO=VE " +
        "RQ=UX RS=TM RU=WC SD=ZL SF=TU SH=VO SL=UT SN=XW SP=YR SR=WX SV=TF TI=YS TO=UC TR=WV " +
        "TS=XR UF=ZT UH=VW UJ=XT UL=YP VF=WS VH=ZG VJ=XN VM=YE VS=WF WI=XF WL=ZP WQ=YU XI=ZN " +
        "XK=YN YH=ZI";

    private const string QuelleEEntries =
        "AA=HE AB=SR AC=PO AD=FJ AE=TL AF=IM AG=RO AH=BD AI=LJ AJ=DK AK=UN AL=CB AM=JQ AN=QV " +
        "AO=ER AP=NS AQ=WT AR=KU AS=VL AT=ZB AU=OJ AV=YX AW=MI AX=GF AY=XU AZ=BP BA=RZ BB=QT " +
        "BC=HA BE=CD BF=NQ BG=TJ BH=DI BI=SP BJ=EU BK=ZD BL=MG BM=GH BN=PR BO=VJ BQ=XW BR=OG " +
        "BS=IP BT=UL BU=WX BV=YZ BW=FM BX=JT BY=LF BZ=KY CA=NO CC=DG CE=OD CF=RM CG=FH CH=UJ " +
        "CI=JO CJ=EP CK=ZF CL=GA CM=LB CN=ME CO=PT CP=YU CQ=ST CR=KW CS=QR CT=VH CU=XZ CV=HG " +
        "CW=IR CX=TO CY=WQ CZ=DP DA=VF DB=EC DC=UH DD=FE DE=TG DF=GK DH=SM DJ=HI DL=RR DM=IJ " +
        "DN=QP DO=JL DQ=PK DR=KQ DS=OM DT=LL DU=NV DV=MK DW=ZH DX=WN DY=XS DZ=YR EA=NL EB=MM " +
        "ED=OO EE=LN EF=PI EG=KN EH=QX EI=JJ EJ=RV EK=IH EL=SW EM=HO EN=TR EO=GP EQ=UF ES=FP " +
        "ET=VO EV=ZJ EW=YP EX=WK EY=XQ EZ=FX FA=GC FB=NI FC=HK FD=OQ FF=IE FG=PV FI=JG FK=QM " +
        "FL=KK FN=RJ FO=LP FQ=SH FR=MB FS=TU FT=ZM FU=YL FV=UQ FW=XN FY=WZ FZ=VR GB=HC GD=ZP " +
        "GE=IB GG=YI GI=JE GJ=XK GL=KH GM=WI GN=LS GO=VT GQ=MP GR=UU GS=NF GT=SD GU=TB GV=OA " +
        "GW=RC GX=PE GY=QI GZ=HW HB=PC HD=OT HF=QE HH=NY HJ=RG HL=MT HM=SY HN=LV HP=TX HQ=KF " +
        "HR=UC HS=JB HT=VZ HU=IA HV=WF HX=ZU HY=XI HZ=YF IC=JA ID=ZZ IF=KC IG=YD II=KS IK=XE " +
        "IL=MW IN=LD IO=WV IQ=NB IS=VW IT=OX IU=PY IV=US IW=QK IX=TE IY=SF IZ=RX JC=QZ JD=PB " +
        "JF=RT JH=OE JI=SA JK=ND JM=TZ JN=MY JP=UW JR=LH JS=VC JU=KA JV=WB JW=ZX JX=YG JY=XA " +
        "JZ=KX KB=SJ KD=RE KE=TV KG=QB KI=UA KJ=PM KL=VY KM=OL KO=WP KP=NW KR=XC KT=MR KV=ZA " +
        "KZ=YB LA=MC LC=ZR LE=NJ LG=YN LI=OH LK=XG LM=PH LO=WD LQ=RA LR=QD LT=VE LU=SC LW=UY " +
        "LX=TT LY=NU LZ=YW MA=SV MD=RF MF=TC MH=QG MJ=UP ML=PF MN=VA MO=NC MQ=OB MS=WH MU=ZT " +
        "MV=YA MX=NZ MZ=XD NA=OZ NE=PA NG=QJ NH=RD NK=SX NM=TF NN=UE NP=VI NR=WG NT=XL NX=YJ " +
        "OC=ZE OF=PG OI=QA OK=RI ON=SK OP=TD OR=UI OS=VX OU=WA OV=XB OW=YE OY=ZW PD=ZG PJ=YC " +
        "PL=XF PN=WE PP=VV PQ=UD PS=TH PU=SZ PW=RK PX=QF PZ=RY QC=RB QH=SE QL=TK QN=UB QO=VD " +
        "QQ=WY QS=XH QU=YH QW=ZC QY=RP RH=ZN RL=YK RN=XJ RQ=WL RS=VG RU=TI RW=UK SB=TM SG=ZK " +
        "SI=UG SL=YM SN=VB SO=XM SQ=WC SS=UZ SU=VK TA=UM TN=VQ TP=WJ TQ=XO TS=YO TW=ZL TY=UX " +
        "UO=VM UR=ZO UT=YS UV=XR VN=WM VP=XT VS=YY VU=ZI WO=XY WR=YQ WS=ZV WU=ZY WW=XP XV=YT " +
        "XX=ZS YV=ZQ";

    private const string QuelleFEntries =
        "AA=WH AB=QN AC=HL AD=SI AE=BG AF=MN AG=DJ AH=UR AI=GP AJ=CQ AK=EO AL=KM AM=VU AN=ZY " +
        "AO=JW AP=IT AQ=TD AR=XC AS=FB AT=YY AU=NV AV=RP AW=OG AX=PH AY=LU AZ=BS BA=RN BB=IQ " +
        "BC=DG BD=LR BE=QQ BF=EK BH=MJ BI=CN BJ=GS BK=SF BL=XG BM=HH BN=TA BO=NZ BP=JT BQ=UO " +
        "BR=OD BT=YV BU=PJ BV=WC BW=KR BX=VY BY=ZW BZ=FD CA=VR CB=HE CC=JY CD=QK CE=DD CF=RS " +
        "CG=WJ CH=EI CI=NS CJ=IO CK=SB CL=GM CM=TF CO=PE CP=MH CR=FF CS=UL CT=XI CU=KV CV=YT " +
        "CW=ZU CX=LP CY=OB CZ=DX DA=JQ DB=TI DC=KK DE=PM DF=EG DH=GV DI=SL DK=FH DL=MR DM=HB " +
        "DN=UW DO=ZS DP=IX DQ=LY DR=NO DS=YZ DT=RV DU=XA DV=WM DW=VO DY=QT DZ=OI EA=KH EB=FJ " +
        "EC=LD ED=GF EE=MC EF=JO EH=IB EJ=HP EL=NM EM=ZQ EN=OL EP=YR EQ=PP ER=XL ES=QH ET=WF " +
        "EU=RY EV=SO EW=VZ EX=TK EY=UU EZ=FA FC=GB FE=NJ FG=HS FI=OO FK=IL FL=PS FM=JK FN=QW " +
        "FO=KZ FP=RJ FQ=LM FR=SQ FS=MV FT=UI FU=TN FV=ZO FW=VA FX=YP FY=XO FZ=WP GA=OQ GC=NH " +
        "GD=PV GE=MA GG=QD GH=LI GI=RF GJ=KC GK=ST GL=JF GN=TQ GO=IH GQ=UB GR=HW GT=VJ GU=ZM " +
        "GW=YN GX=WS GY=XQ GZ=HA HC=ZK HD=NE HF=YK HG=OT HI=XS HJ=PB HK=WV HM=QY HN=VG HO=RD " +
        "HQ=UF HR=TU HT=SW HU=IZ HV=MW HX=JI HY=LW HZ=KT IA=JC IC=ZH ID=KE IE=YH IF=LA IG=XX " +
        "II=MT IJ=WY IK=NC IM=VD IN=OW IP=UZ IR=PY IS=TW IU=QB IV=SD IW=RH IY=JZ JA=QF JB=PA " +
        "JD=RC JE=OZ JG=SY JH=NQ JJ=TS JL=ME JM=UD JN=LF JP=VL JR=KP JS=WZ JU=ZF JV=XE JX=YF " +
        "KA=NF KB=LC KD=MF KF=OR KG=PD KI=ZB KJ=QZ KL=YC KN=RA KO=XU KQ=SM KS=WR KU=TY KW=VF " +
        "KX=UJ KY=LZ LB=ZD LE=MP LG=NK LH=YA LJ=OX LK=XZ LL=WB LN=PF LO=VC LQ=RK LS=QI LT=UG " +
        "LV=SH LX=TG MB=SN MD=RX MG=TB MI=QC MK=UA ML=PK MM=VX MO=WD MQ=RE MS=QP MU=XF MX=ZZ " +
        "MY=NX MZ=YL NA=ZV NB=YD ND=OE NG=PI NI=XH NL=QG NN=WQ NP=RL NR=VK NT=SA NU=TR NW=UM " +
        "NY=OV OA=PL OC=QE OF=RI OH=SE OJ=TZ OK=US OM=VH ON=WA OP=XY OS=YQ OU=ZI OY=PZ PC=TE " +
        "PG=SJ PN=UH PO=RG PQ=VB PR=QL PT=WK PU=XK PW=YI PX=ZN QA=ZT QJ=RO QM=YS QO=SP QR=WE " +
        "QS=XB QU=TH QV=UK QX=VP RB=SZ RM=TT RQ=UV RR=VV RT=WX RU=ZL RW=YU RZ=XT SC=ZA SG=YJ " +
        "SK=XJ SR=WN SS=VM SU=TV SV=UN SX=TC TJ=YO TL=XM TM=ZP TO=VN TP=WO TX=UQ UC=VW UE=WT " +
        "UP=XR UT=YW UX=ZR UY=VE VI=ZJ VQ=YM VS=XP VT=WU WG=XV WI=ZG WL=YX WW=XD XN=ZC XW=YG " +
        "YB=ZE YE=ZX";

    private const string QuelleGEntries =
        "AA=HW AB=WH AC=NL AD=BM AE=UP AF=GJ AG=DQ AH=ZI AI=MO AJ=CB AK=ID AL=QF AM=KU AN=ST " +
        "AO=YW AP=JY AQ=OZ AR=EV AS=FX AT=RP AU=XJ AV=LL AW=VN AX=PT AY=TO AZ=BB BA=RM BC=DO " +
        "BD=WE BE=GH BF=PQ BG=KR BH=SW BI=HT BJ=MM BK=QI BL=FU BN=ZG BO=JV BP=OW BQ=IG BR=TL " +
        "BS=LP BT=NR BU=YT BV=UM BW=XF BX=ES BY=VR BZ=CM CA=PO CC=MJ CD=OT CE=DM CF=LJ CG=EP " +
        "CH=NU CI=VL CJ=FS CK=QM CL=KO CN=GE CO=JT CP=RR CQ=ZD CR=TI CS=TY CT=WB CU=YR CV=SX " +
        "CW=UJ CX=IH CY=XD CZ=HV DA=NB DB=EA DC=KE DD=FP DE=LH DF=QC DG=OQ DH=SR DI=GL DJ=MH " +
        "DK=HR DL=JZ DN=PM DP=ZK DR=TG DS=YO DT=RK DU=IL DV=US DW=VU DX=WJ DY=XM DZ=EY EB=OO " +
        "EC=MQ ED=FC EE=LF EF=HP EG=PV EH=ZM EI=NW EJ=YL EK=QO EL=XP EM=KJ EN=RT EO=VX EQ=SP " +
        "ER=GN ET=IB EU=JR EW=TS EX=UV EZ=WM FA=MS FB=QK FD=LR FE=GP FF=ZA FG=HM FH=KL FI=NZ " +
        "FJ=YY FK=JO FL=OM FM=IN FN=XR FO=PX FQ=WP FR=TW FT=UY FV=RI FW=VZ FY=SN FZ=GA GB=OK " +
        "GC=NJ GD=PI GF=MU GG=QQ GI=LT GK=RV GM=KA GO=SI GQ=JH GR=TU GS=IJ GT=UH GU=ZP GV=YJ " +
        "GW=VI GX=WR GY=XT GZ=HJ HA=MF HB=IP HC=LN HD=JL HE=KG HF=NO HG=ZR HH=OV HI=YG HK=XG " +
        "HL=PK HN=QG HO=RF HQ=WU HS=TE HU=SK HX=UO HY=VT HZ=IX IA=RD IC=QE IE=SG IF=PC II=TD " +
        "IK=OJ IM=UF IO=NH IQ=VG IR=MW IS=WO IT=LV IU=XC IV=KQ IW=YM IY=ZO IZ=JX JA=KC JB=ZF " +
        "JC=LD JD=YE JE=MA JF=XI JG=NE JI=WF JJ=OG JK=VW JM=PF JN=UD JP=QA JQ=TB JS=RB JU=TC " +
        "JW=SD KB=SC KD=RE KF=UZ KH=TF KI=QD KK=PD KM=VV KN=OE KP=WY KS=NQ KT=XB KV=MZ KW=LX " +
        "KX=ZW KY=LW KZ=YX LA=MC LB=ZZ LC=YD LE=NX LG=XK LI=OB LK=WW LM=PR LO=VP LQ=RH LS=QT " +
        "LU=TR LY=UU LZ=VS MB=SF MD=RG ME=TK MG=QJ MI=UX MK=PL ML=VE MN=OR MP=WC MR=ND MT=XX " +
        "MV=ZN MX=YV MY=NV NA=OY NC=ZV NF=PH NG=YP NI=QH NK=XY NM=RW NN=WL NP=SO NS=VK NT=UQ " +
        "NY=TT OA=TH OC=SJ OD=UL OF=RN OH=VM OI=QZ OL=WK ON=PU OP=XS OS=ZU OU=YN OX=WS PA=ZT " +
        "PB=XA PE=YI PG=WI PJ=QL PN=VJ PP=RL PS=TV PW=SY PY=UW PZ=XW QB=RZ QN=ZY QP=SV QR=YU " +
        "QS=TP QU=XO QV=UN QW=RA QX=VY QY=ZB RC=SE RJ=YQ RO=ZX RQ=TM RS=XN RU=VQ RX=UI RY=WT " +
        "SA=TZ SB=ZQ SH=YK SL=XZ SM=WQ SQ=VA SS=UT SU=TX SZ=YA TA=UR TJ=VH TN=WZ TQ=XU UA=WG " +
        "UB=VC UC=XH UE=YH UG=ZL UK=VO VB=ZS VD=WA VF=YC WD=XE WN=YS WV=ZJ WX=YZ XL=ZH XQ=YF " +
        "XV=ZE YB=ZC";
}
