using Enigma.Reflectors;
using Enigma.Rotors;

namespace Enigma.Tests;

public class EnigmaMachineTests
{
    private static readonly ICharacterMap CharacterMap = new DefaultCharacterMap();

    private static EnigmaMachine BuildMachine(params IRotor[] rotors) =>
        new(new PlugBoard(CharacterMap), rotors, new ReflectorB());

    private static string Translate(IEnigmaMachine machine, string text)
    {
        var input = text.Select(CharacterMap.GetIndex);

        return string.Concat(machine.Translate(input).Select(CharacterMap.GetCharacter));
    }

    [Fact]
    public void Translate_MatchesTheKnownVectorForRotorsOneTwoThree()
    {
        var machine = BuildMachine(new RotorI(), new RotorII(), new RotorIII());

        Assert.Equal("BDZGO", Translate(machine, "AAAAA"));
    }

    [Fact]
    public void Translate_MatchesTheKnownVectorAcrossTheFastRotorTurnover()
    {
        // 26 characters carries rotor III past its turnover at V, stepping the middle rotor.
        var machine = BuildMachine(new RotorI(), new RotorII(), new RotorIII());

        Assert.Equal("BDZGOWCXLTKSBTMCDLPBMUQOFX", Translate(machine, new string('A', 26)));
    }

    // Generated by an independent reference implementation written from the pawl
    // mechanics, itself anchored on the two known vectors above; its first 26
    // characters are the published 26-character vector.
    private const string LongVector =
        "BDZGOWCXLTKSBTMCDLPBMUQOFXYHCXTGYJFLINHNXSHIUNTHEORXPQPKOVHCBUBTZSZSOOST" +
        "GOTFSODBBZZLXLCYZXIFGWFDZEEQIBMGFJBWZFCKPFMGBXQCIVIBBRNCOCJUVYDKMVJPFMDR" +
        "MTGLWF";

    [Fact]
    public void Translate_MatchesTheKnownVectorAcrossTheMiddleRotorTurnover()
    {
        // 150 characters carries the middle rotor onto its own notch at keypress 101,
        // which is the only point where the double step is exercised.
        var machine = BuildMachine(new RotorI(), new RotorII(), new RotorIII());

        Assert.Equal(LongVector, Translate(machine, new string('A', 150)));
    }

    [Fact]
    public void Translate_LeavesTheRotorsWhereTheLongVectorExpects()
    {
        var rotors = new IRotor[] { new RotorI(), new RotorII(), new RotorIII() };
        var machine = BuildMachine(rotors);

        Translate(machine, new string('A', 150));

        // Window reads B G U: the left rotor has moved exactly once, at the double step.
        Assert.Equal([1, 6, 20], rotors.Select(rotor => rotor.Position));
    }

    [Fact]
    public void Translate_MovesTheLeftRotorExactlyOnceInAHundredAndFiftyKeypresses()
    {
        var rotors = new IRotor[] { new RotorI(), new RotorII(), new RotorIII() };
        var machine = BuildMachine(rotors);

        var moves = 0;
        var previous = rotors[0].Position;

        for (var i = 0; i < 150; i++)
        {
            machine.Translate(0);

            if (rotors[0].Position != previous)
            {
                moves++;
                previous = rotors[0].Position;
            }
        }

        Assert.Equal(1, moves);
    }

    [Fact]
    public void Translate_IsReciprocal()
    {
        const string message = "ATTACKATDAWNTHEENEMYISADVANCINGONTHEEASTERNFRONTSENDREINFORCEMENTS";

        var encrypting = BuildMachine(new RotorI(), new RotorII(), new RotorIII());
        var decrypting = BuildMachine(new RotorI(), new RotorII(), new RotorIII());

        var cipher = Translate(encrypting, message);

        Assert.Equal(message, Translate(decrypting, cipher));
    }

    [Fact]
    public void Translate_NeverEncryptsALetterToItself()
    {
        // The defining weakness of the machine, and a sharp check on the reflector wiring.
        var machine = BuildMachine(new RotorI(), new RotorII(), new RotorIII());
        var message = string.Concat(Enumerable.Repeat("ABCDEFGHIJKLMNOPQRSTUVWXYZ", 8));

        var cipher = Translate(machine, message);

        Assert.All(message.Zip(cipher), pair => Assert.NotEqual(pair.First, pair.Second));
    }

    [Fact]
    public void Translate_AdvancesTheFastRotorOnEveryCharacter()
    {
        var machine = BuildMachine(new RotorI(), new RotorII(), new RotorIII());
        var fast = machine.Rotors.Last();

        machine.Translate(0);
        Assert.Equal(1, fast.Position);

        machine.Translate(0);
        Assert.Equal(2, fast.Position);
    }

    [Fact]
    public void Translate_DoubleStepsTheMiddleRotor()
    {
        // Starting at A D U, the middle rotor steps on consecutive keypresses:
        // the second because the fast rotor is on its turnover, the third because
        // the middle rotor is on its own, which drags the left rotor round with it.
        var rotors = new IRotor[] { new RotorI(), new RotorII(), new RotorIII() };
        var machine = BuildMachine(rotors);

        rotors[0].SetPosition(0);  // A
        rotors[1].SetPosition(3);  // D
        rotors[2].SetPosition(20); // U

        machine.Translate(0);
        Assert.Equal([0, 3, 21], rotors.Select(rotor => rotor.Position));

        machine.Translate(0);
        Assert.Equal([0, 4, 22], rotors.Select(rotor => rotor.Position));

        machine.Translate(0);
        Assert.Equal([1, 5, 23], rotors.Select(rotor => rotor.Position));
    }

    [Fact]
    public void Translate_LeavesTheLeftRotorAloneUntilTheMiddleOneTurnsOver()
    {
        var rotors = new IRotor[] { new RotorI(), new RotorII(), new RotorIII() };
        var machine = BuildMachine(rotors);

        for (var i = 0; i < 20; i++)
        {
            machine.Translate(0);
        }

        Assert.Equal(0, rotors[0].Position);
    }

    [Fact]
    public void Translate_EnumeratesTheInputExactlyOnce()
    {
        // Deferred execution would let the rotors step again on a second enumeration.
        var machine = BuildMachine(new RotorI(), new RotorII(), new RotorIII());

        var result = machine.Translate(Enumerable.Repeat(0, 3));

        Assert.Equal(result.ToList(), result.ToList());
    }

    [Fact]
    public void PlugBoardPatching_ChangesTheOutputAndStaysReciprocal()
    {
        const string message = "AAAAA";

        var plain = BuildMachine(new RotorI(), new RotorII(), new RotorIII());

        var patched = new EnigmaMachine(
            new PlugBoard(CharacterMap),
            [new RotorI(), new RotorII(), new RotorIII()],
            new ReflectorB());
        patched.PlugBoard.Connect(0, 25);

        var decrypting = new EnigmaMachine(
            new PlugBoard(CharacterMap),
            [new RotorI(), new RotorII(), new RotorIII()],
            new ReflectorB());
        decrypting.PlugBoard.Connect(0, 25);

        var cipher = Translate(patched, message);

        Assert.NotEqual(Translate(plain, message), cipher);
        Assert.Equal(message, Translate(decrypting, cipher));
    }

    [Fact]
    public void ReflectorC_ProducesADifferentCipherThanReflectorB()
    {
        var withB = BuildMachine(new RotorI(), new RotorII(), new RotorIII());

        var withC = new EnigmaMachine(
            new PlugBoard(CharacterMap),
            [new RotorI(), new RotorII(), new RotorIII()],
            new ReflectorC());

        Assert.NotEqual(Translate(withB, "AAAAA"), Translate(withC, "AAAAA"));
    }

    [Theory]
    [InlineData("B", "YRUHQSLDPXNGOKMIEBFZCWVJAT")]
    [InlineData("C", "FVPJIAOYEDRZXWGCTKUQSBNMHL")]
    public void Reflectors_ArePairedAndNeverMapALetterToItself(string name, string _)
    {
        IReflector reflector = name == "B" ? new ReflectorB() : new ReflectorC();

        for (var input = 0; input < CharacterMap.Count; input++)
        {
            var output = reflector.Translate(input);

            Assert.NotEqual(input, output);
            Assert.Equal(input, reflector.Translate(output));
        }
    }

    [Fact]
    public void Constructor_RejectsAMachineWithNoRotors()
    {
        var exception = Assert.Throws<ArgumentException>(
            () => new EnigmaMachine(new PlugBoard(CharacterMap), [], new ReflectorB()));

        Assert.Equal("rotors", exception.ParamName);
    }
}
